export enum Action {
    SETAUTH = "setAuth",
    SETUSER = "setUser",
    DELETETODO = "deleteTodo",
    UPDATEDATETODO = "updateDateTodo",
    UPDATENAMETODO = "updateNameTodo",
    COMPLETETODO = "completeTodo",
    CREATETODO = "createTodo",
    DELETECOMPLETETODOS = "deleteCompleteTodos",
    CREATESUBTODO= "createSubTodo",
    COMPLETESUBTODO = "completeSubTodo",
    DELETESUBTODO = "deleteSubTodo",
    COMPLETEALLTODOS = "completeAllTodos",
    FETCHTODOS = "fetchTodos",
    HANDLEONDRAGEND = "handleOnDragEnd",
    DELETEACCOUNT = "deleteAccount",
    CHANGEDETAILS = "changeDetails",
}